project:
  output-dir: docs
  resources:
  - CNAME
  type: website
website:
  navbar:
    left:
    - href: index.qmd
      text: Home
    - href: about.qmd
      text: Sobre
  sidebar:
    collapse-level: 1
    contents:
    - contents:
      - href: conteudos/linha-de-comando/1-pwd.md
        text: âœ… Pwd
      - href: conteudos/linha-de-comando/2-cd.md
        text: âœ… Cd
      - href: conteudos/linha-de-comando/3-ls.md
        text: âœ… Ls
      - href: conteudos/linha-de-comando/4-touch.md
        text: âœ… Touch
      - href: conteudos/linha-de-comando/5-file.md
        text: âœ… File
      - href: conteudos/linha-de-comando/6-cat.md
        text: âœ… Cat
      - href: conteudos/linha-de-comando/7-less.md
        text: âœ… Less
      - href: conteudos/linha-de-comando/8-history.md
        text: âœ… History
      - href: conteudos/linha-de-comando/9-cp.md
        text: âœ… Cp
      - href: conteudos/linha-de-comando/10-mv.md
        text: âœ… Mv
      - href: conteudos/linha-de-comando/11-mkdir.md
        text: âœ… Mkdir
      - href: conteudos/linha-de-comando/12-rm.md
        text: âœ… Rm
      - href: conteudos/linha-de-comando/13-man.md
        text: âœ… Man
      - href: conteudos/linha-de-comando/14-find.md
        text: âœ… Find
      section: ðŸ“‚ Linha De Comando
    - contents:
      - href: conteudos/arte-do-texto/1-stdout.md
        text: âœ… Stdout
      - href: conteudos/arte-do-texto/2-stdin.md
        text: âœ… Stdin
      - href: conteudos/arte-do-texto/3-stderr.md
        text: âœ… Stderr
      - href: conteudos/arte-do-texto/4-pipe_and_tee.md
        text: âœ… Pipe_And_Tee
      - href: conteudos/arte-do-texto/5-env.md
        text: âœ… Env
      - href: conteudos/arte-do-texto/6-cut.md
        text: âœ… Cut
      - href: conteudos/arte-do-texto/7-head.md
        text: âœ… Head
      - href: conteudos/arte-do-texto/8-paste.md
        text: âœ… Paste
      - href: conteudos/arte-do-texto/9-grep.md
        text: âœ… Grep
      - href: conteudos/arte-do-texto/10-sort.md
        text: âœ… Sort
      - href: conteudos/arte-do-texto/11-tail.md
        text: âœ… Tail
      - href: conteudos/arte-do-texto/12-tr.md
        text: âœ… Tr
      - href: conteudos/arte-do-texto/13-uniq.md
        text: âœ… Uniq
      - href: conteudos/arte-do-texto/14-sed.md
        text: âœ… Sed
      section: ðŸ“‚ Arte Do Texto
    - contents:
      - href: conteudos/manipulacao-de-usuario/1- Usuario e grupo.md
        text: âœ… Usuario E Grupo
      - href: conteudos/manipulacao-de-usuario/2- root.md
        text: âœ… Root
      - href: conteudos/manipulacao-de-usuario/3- Arquivo passwd.md
        text: âœ… Arquivo Passwd
      - href: conteudos/manipulacao-de-usuario/4- Arquivo shadow.md
        text: âœ… Arquivo Shadow
      - href: conteudos/manipulacao-de-usuario/5- Arquivo group.md
        text: âœ… Arquivo Group
      - href: conteudos/manipulacao-de-usuario/6- Gerenciamento de usuÃ¡rios.md
        text: âœ… Gerenciamento De UsuÃ¡rios
      section: ðŸ“‚ Manipulacao De Usuario
    - contents:
      - href: conteudos/processos/1- Comando ps.md
        text: âœ… Comando Ps
      - href: conteudos/processos/2 - Controlando o Terminal.md
        text: âœ… Controlando O Terminal
      - href: conteudos/processos/3 - Sobre processos.md
        text: âœ… Sobre Processos
      - href: conteudos/processos/4 - CriaÃ§Ã£o de processos.md
        text: âœ… CriaÃ§Ã£o De Processos
      - href: conteudos/processos/5 - FinalizaÃ§Ã£o de processos.md
        text: âœ… FinalizaÃ§Ã£o De Processos
      - href: conteudos/processos/6 - Sinais no Linux.md
        text: âœ… Sinais No Linux
      - href: conteudos/processos/7 - kill(Terminate).md
        text: âœ… Kill(Terminate)
      - href: conteudos/processos/8 - niceness.md
        text: âœ… Niceness
      - href: conteudos/processos/9 - Controle de Job.md
        text: âœ… Controle De Job
      - href: conteudos/processos/10 - _proc filesystem.md
        text: âœ… Proc Filesystem
      - href: conteudos/processos/11 - Status de processos.md
        text: âœ… Status De Processos
      section: ðŸ“‚ Processos
    - contents:
      - href: conteudos/pacotes/1 - DistribuiÃ§Ã£o de programas.md
        text: âœ… DistribuiÃ§Ã£o De Programas
      - href: conteudos/pacotes/2 - RepositÃ³rios.md
        text: âœ… RepositÃ³rios
      - href: conteudos/pacotes/3 - Arquivos Tar e Zip.md
        text: âœ… Arquivos Tar E Zip
      - href: conteudos/pacotes/4 - DependÃªncia de pacotes.md
        text: âœ… DependÃªncia De Pacotes
      - href: conteudos/pacotes/5 - RPM e dpkg.md
        text: âœ… Rpm E Dpkg
      - href: conteudos/pacotes/6 - Yum e Apt.md
        text: âœ… Yum E Apt
      - href: conteudos/pacotes/7 - Compilando.md
        text: âœ… Compilando
      section: ðŸ“‚ Pacotes
    - contents:
      - href: conteudos/permissoes/1 - PermissÃµes.md
        text: âœ… PermissÃµes
      - href: conteudos/permissoes/2 - Modificando PermissÃµes.md
        text: âœ… Modificando PermissÃµes
      - href: conteudos/permissoes/3 - Alterando proprietÃ¡rio.md
        text: âœ… Alterando ProprietÃ¡rio
      - href: conteudos/permissoes/4 - Umask.md
        text: âœ… Umask
      - href: conteudos/permissoes/5 - Setuid.md
        text: âœ… Setuid
      - href: conteudos/permissoes/6 - Setgid.md
        text: âœ… Setgid
      - href: conteudos/permissoes/7 - ProcessPermissions.md
        text: âœ… Processpermissions
      - href: conteudos/permissoes/8 - Sticky Bit.md
        text: âœ… Sticky Bit
      section: ðŸ“‚ Permissoes
    - contents:
      - href: conteudos/troubleshooting/1-ICMP.md
        text: âœ… Icmp
      - href: conteudos/troubleshooting/2-ping.md
        text: âœ… Ping
      - href: conteudos/troubleshooting/3-traceroute.md
        text: âœ… Traceroute
      - href: conteudos/troubleshooting/4-netstat.md
        text: âœ… Netstat
      - href: conteudos/troubleshooting/5-Analise-de-pacotes.md
        text: âœ… Analise-De-Pacotes
      section: ðŸ“‚ Troubleshooting
    - contents:
      - href: conteudos/compartilhamento/1-compartilhando-arquivos.md
        text: âœ… Compartilhando-Arquivos
      - href: conteudos/compartilhamento/2-rsync.md
        text: âœ… Rsync
      - href: conteudos/compartilhamento/3-SimpleHTTPServer.md
        text: âœ… Simplehttpserver
      - href: conteudos/compartilhamento/4-NFS.md
        text: âœ… Nfs
      - href: conteudos/compartilhamento/5-Samba.md
        text: âœ… Samba
      section: ðŸ“‚ Compartilhamento
    - contents:
      - href: conteudos/configurar-rede/1-interfaces-de-rede.md
        text: âœ… Interfaces-De-Rede
      - href: conteudos/configurar-rede/2-route.md
        text: âœ… Route
      - href: conteudos/configurar-rede/3-dhclient.md
        text: âœ… Dhclient
      - href: conteudos/configurar-rede/4-NetworkManager.md
        text: âœ… Networkmanager
      - href: conteudos/configurar-rede/5-arp.md
        text: âœ… Arp
      section: ðŸ“‚ Configurar Rede
    search: true
    style: docked
  title: linuxteclab
